spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  application:
    name: springcloud-config-client-dev


---
spring:
  profiles: test
  application:
    name: springcloud-config-client-test